# Configuration documentation:
# https://docs.getnao.io/nao-agent/context-builder/configuration#nao_config-yaml

project_name: BKNAO
databases:
- type: snowflake
  name: snowflake-prod
  include: []
  exclude: []
  accessors:
  - columns
  - description
  - preview
  username: USR_LLM_X
  account_id: BQ04028-BK
  password: RBzXMAsOhiTJo7
  database: POC_LLM_X
  schema_name: POC_IA_COMO
  warehouse: WH_POC_LLM_X
- type: postgres
  name: postgres-prod
  include: []
  exclude: []
  accessors:
  - columns
  - description
  - preview
  host: 192.168.2.17
  port: 5432
  database: Agendis4-SDIS77
  user: admin
  password: KEhPp7RMhbwR9z*hFfCo
  schema_name: Agendis
- type: fabric
  name: fabric-emc
  include: []
  exclude: []
  accessors:
  - columns
  - description
  - preview
  host: {{ env('FABRIC_HOST') }}
  port: 1433
  database: {{ env('FABRIC_DATABASE') }}
  auth_mode: azure_service_principal
  client_id: {{ env('FABRIC_CLIENT_ID') }}
  client_secret: {{ env('FABRIC_CLIENT_SECRET') }}
  tenant_id: {{ env('FABRIC_TENANT_ID') }}
  driver: ODBC Driver 18 for SQL Server
repos: []
